version: '2'

services:

  php-fpm:
    build: ./php-fpm
    volumes_from:
      - application
    expose:
      - "9000"

  application:
    build: ./application
    volumes:
      - ../:/var/www/opencart

  data:
    build: ./data
    volumes:
      - ./database/mysql:/var/lib/mysql

  nginx:
    build: ./nginx
    volumes_from:
      - application
    volumes:
      - ./logs/nginx/:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - php-fpm

  apache:
    build: ./apache
    volumes_from:
      - application
    volumes:
      - ./logs/apache:/var/log/apache2
    ports:
      - "80:80"

  mysql:
    image: mysql:latest
    volumes_from:
      - data
    restart: always
    environment:
      MYSQL_DATABASE: opencart
      MYSQL_USER: opencart
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root

  mariadb:
    image: mariadb:latest
    volumes_from:
      - data
    restart: always
    environment:
      MYSQL_DATABASE: opencart
      MYSQL_USER: opencart
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
